### ISSUE TITLE
"Code" tag is somewhat flawed

### ISSUE THREAD

**Issue by Arano-kai** [colobot/colobot#1029]
Ver: 0.1.10
OS: Debian (stretch)
![bugs in c tag](https://user-images.githubusercontent.com/1828919/29392108-6a9550f8-8304-11e7-94a6-2db34b0c7420.png)
* Red rectangle - in-line `\c` has no effect.
* Yellow arrow - self explanatory; there is no such glitch in `0.1.9`.

**Comment by krzys-h** [comment]
I fixed the margin glitch.

In-line `\c;` does have an effect - it makes the font monospace, though it may be slightly hard to see, that may improve after planned font changes (see #1019). The thing that adds the background is `\s;` I think.

**Comment by tomangelo2** [comment]
Still present in current dev, depends of set game resolution
