### ISSUE TITLE
Came crashed because object outlived its own class

### ISSUE THREAD

**Issue by hexagonrecursion** [colobot/colobot#1686]
An instance of a class can outlive the class itself. All methods of the instance appear to become no-ops that return nothing. This violates type safety and cause the game to crash in some cases.

## To reproduce

1. Spawn two bots
2. Add the below program to the first bot
    ```c++
    public class Foo
    {
    	string Bar()
    	{
    		return "Foo.Bar";
    	}
    }
    
    extern void Def()
    {
    }
    ```
3. Run the below program on the second bot
    ```c++
    extern void Use()
    {
    	Foo foo = new Foo;
    	while(true) {
    		wait(1);
    		message(foo.Bar());
    	}
    }
    ```
4. Switch back to the fist bot and delete the first program or destroy the first bot.
5. Get "Thread 1 "colobot" received signal SIGSEGV, Segmentation fault."

## Expected

1. The game does not crash
2. Attempting to call a method of a class that no longer exists should probably be a runtime error like div by zero

## Stacktrace

#0  0x000055555577c317 in CScriptFunctions::rMessage (var=0x0, result=0x555557cdaca0, exception=@0x7fffffffbba4: 0, user=0x55555630f570) at /home/cdda/git/colobot/src/script/scriptfunc.cpp:2896
#1  0x000055555596dadb in CBot::CBotExternalCallDefault::Run (this=0x5555560042f0, thisVar=0x0, pStack=0x555557cb6b98) at /home/cdda/git/colobot/src/CBot/CBotExternalCall.cpp:160
#2  0x000055555596d750 in CBot::CBotExternalCallList::DoCall (this=0x555555ffb910, token=0x555557cb33c8, thisVar=0x0, ppVar=0x7fffffffbda0, pStack=0x555557cb6b98, rettype=...)
    at /home/cdda/git/colobot/src/CBot/CBotExternalCall.cpp:104
#3  0x0000555555990213 in CBot::CBotStack::ExecuteCall (this=0x555557cb6b98, nIdent=@0x555557cb3480: 0, token=0x555557cb33c8, ppVar=0x7fffffffbda0, rettype=...)
    at /home/cdda/git/colobot/src/CBot/CBotStack.cpp:608
#4  0x00005555559cd60a in CBot::CBotInstrCall::Execute (this=0x555557cb33c0, pj=@0x7fffffffdd28: 0x555557cb6a60) at /home/cdda/git/colobot/src/CBot/CBotInstr/CBotInstrCall.cpp:156
#5  0x00005555559d0798 in CBot::CBotListInstr::Execute (this=0x555557cb1bd0, pj=@0x7fffffffdd60: 0x555557cb69f8) at /home/cdda/git/colobot/src/CBot/CBotInstr/CBotListInstr.cpp:91
#6  0x000055555598b34b in CBot::CBotWhile::Execute (this=0x555557c40830, pj=@0x7fffffffdd98: 0x555557cb6990) at /home/cdda/git/colobot/src/CBot/CBotInstr/CBotWhile.cpp:112
#7  0x00005555559d0798 in CBot::CBotListInstr::Execute (this=0x555557ca1aa0, pj=@0x7fffffffdde8: 0x555557cb6928) at /home/cdda/git/colobot/src/CBot/CBotInstr/CBotListInstr.cpp:91
#8  0x000055555597695a in CBot::CBotFunction::Execute (this=0x555557cb6180, ppVars=0x0, pj=@0x555557c40fc8: 0x555557cb68c0, pInstance=0x555557bb6180)
    at /home/cdda/git/colobot/src/CBot/CBotInstr/CBotFunction.cpp:448
#9  0x000055555598c728 in CBot::CBotProgram::Run (this=0x555557c40f90, pUser=0x55555630f570, timer=100) at /home/cdda/git/colobot/src/CBot/CBotProgram.cpp:198
#10 0x000055555591cae3 in CScript::Continue (this=0x55555630f570) at /home/cdda/git/colobot/src/script/script.cpp:366
#11 0x0000555555893942 in CProgrammableObjectImpl::EventProcess (this=0x555557bbce68, event=...) at /home/cdda/git/colobot/src/object/implementation/programmable_impl.cpp:81
#12 0x000055555574477c in COldObject::EventProcess (this=0x555557bbcd70, event=...) at /home/cdda/git/colobot/src/object/old_object.cpp:2341
#13 0x00005555556d3ecb in CRobotMain::EventFrame (this=0x555555ff4140, event=...) at /home/cdda/git/colobot/src/level/robotmain.cpp:2380
#14 0x00005555556ccd1d in CRobotMain::ProcessEvent (this=0x555555ff4140, event=...) at /home/cdda/git/colobot/src/level/robotmain.cpp:693
#15 0x00005555555b7bf4 in CController::ProcessEvent (this=0x555555e6d740, event=...) at /home/cdda/git/colobot/src/app/controller.cpp:56
#16 0x00005555555a4976 in CApplication::Run (this=0x7fffffffe5a0) at /home/cdda/git/colobot/src/app/app.cpp:1194
#17 0x000055555559b8bc in main (argc=1, argv=0x7fffffffe968) at /home/cdda/git/colobot/src/app/main.cpp:199

Crash is on line 2896 in `message()` because `var` is `null`
```
p = var->GetValString();
```

## Version

colobot-gold-0.2.1-alpha acc3c5ae5e6474565b53b9527d4b00c6f36a1d15

**Comment by hexagonrecursion** [comment]
I think the source of the bug might be here

https://github.com/colobot/colobot/blob/d56c7dbfda6f87074aac8ffee1e22264caa01c32/CBot/src/CBot/CBotClass.cpp#L325-L343

If we can not find the method anywhere we return true. We should call SetError() instead.

**Comment by hexagonrecursion** [comment]
Editing the class to remove or rename the method also leads to a crash.

**Comment by melex750** [comment]
Thanks for reporting, fixed in my WIP...

**Comment by hexagonrecursion** [comment]
* I can still reproduce the crash in https://github.com/melex750/colobot/pull/2
