### ISSUE TITLE
Misleading CBot compilation error

### ISSUE THREAD

**Issue by tr00per** [colobot/colobot#385]
When you try to compile a function with no return type

```
object::someFunction()
```

the compiler error says

> Brakująca nazwa funkcji (Missing function name)

and the editor mark is put on the double-colon, which is clearly misleading.

**Comment by piotrwalkusz1** [comment]
Should this was fixed? Some programming languages have nested classes (yes, I know that CBot doesn't have this), so this code makes sense
```
ParentClass::NestedClass object::Foo()
```
Function `Foo` is method of class `object` and return `NestedClass` that is nested class of `ParentClass`. If we delete object::Foo
```
ParentClass::NestedClass()
```
 error `Missing function name` makes sence. Of course if we intend introduce nested classes.

**Comment by B-CE** [comment]
the issue is still there in 1.11 & current dev version.

However, an already translated string tell : 
> Function needs return type \"void\" 

instead, this is the following string that is called:
> Function name missing

without the "object::" , it's this one that is called:
> Type declaration missing
