### ISSUE TITLE
Starting first mission. SIGSEGV, segmentation fault

### ISSUE THREAD

**Issue by micahn** [colobot/colobot#864]
trying to start the first mission after installing the build from ubuntu's repository.
running on ubuntu 16.10

Crashes during loading first mission. seems to be during object loading.
Free game does work.

here is the console log during loading and the crash.

[INFO]: Loading level: levels/missions/chapter001/level001/scene.txt
[WARN]: This level is using deprecated way of defining win scene. Please change the win= parameter in EndingFile from 101 to "levels/other/win101.txt".
[WARN]: This level is using deprecated way of defining lost scene. Please change the lost= parameter in EndingFile from 0 to "levels/other/lost000.txt".
[ERROR]: Error opening file with PHYSFS: "textures/shadow00.png"
[ERROR]: Couldn't load texture 'textures/shadow00.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow01.png"
[ERROR]: Couldn't load texture 'textures/shadow01.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow02.png"
[ERROR]: Couldn't load texture 'textures/shadow02.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow03.png"
[ERROR]: Couldn't load texture 'textures/shadow03.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow04.png"
[ERROR]: Couldn't load texture 'textures/shadow04.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow05.png"
[ERROR]: Couldn't load texture 'textures/shadow05.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow06.png"
[ERROR]: Couldn't load texture 'textures/shadow06.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow07.png"
[ERROR]: Couldn't load texture 'textures/shadow07.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow08.png"
[ERROR]: Couldn't load texture 'textures/shadow08.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow09.png"
[ERROR]: Couldn't load texture 'textures/shadow09.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow10.png"
[ERROR]: Couldn't load texture 'textures/shadow10.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow11.png"
[ERROR]: Couldn't load texture 'textures/shadow11.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow12.png"
[ERROR]: Couldn't load texture 'textures/shadow12.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow13.png"
[ERROR]: Couldn't load texture 'textures/shadow13.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow14.png"
[ERROR]: Couldn't load texture 'textures/shadow14.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow15.png"
[ERROR]: Couldn't load texture 'textures/shadow15.png': Unable to open file, blacklisting

==============================
You seem to be running a custom compilation of version 0.1.8-alpha, but please verify that.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=1 rank=1
==============================

**Comment by tomangelo2** [comment]
You have version 0.1.8 so I assume that it's caused by #828, which is fixed in current release. Ubuntu repositories doesn't have version 0.1.9 yet.

**Comment by Ryah** [comment]
Ubuntu 16.10 still only has version 0.1.8-2build1 in the software installer, so I'm still getting the crash.

**Comment by krzys-h** [comment]
Ubuntu won't update until the next release of the OS, you need to use this PPA: https://launchpad.net/~odyx/+archive/ubuntu/colobot
