### ISSUE TITLE
MacOS X compile error: no 'CSingleton<CLogger>::m_instance' definition is available

### ISSUE THREAD

**Issue by hlopetz** [colobot/colobot#966]
hi there,

following [these instructions](https://github.com/colobot/colobot/blob/master/INSTALL-MacOSX.md) hit this bug on `make` step:

```
$ make
Scanning dependencies of target localename
[  0%] Building C object lib/localename/CMakeFiles/localename.dir/localename.c.o
[  0%] Linking C static library liblocalename.a
[  0%] Built target localename
Scanning dependencies of target colobotbase
[  0%] Building CXX object src/CMakeFiles/colobotbase.dir/sound/oalsound/alsound.cpp.o
In file included from .../src/sound/oalsound/alsound.cpp:21:
In file included from .../src/sound/oalsound/alsound.h:32:
In file included from .../src/sound/oalsound/channel.h:31:
In file included from .../src/sound/oalsound/check.h:22:
In file included from .../src/common/logger.h:28:
.../src/common/singleton.h:44:16: error: instantiation of variable 'CSingleton<CLogger>::m_instance' required here, but no definition is available
      [-Werror,-Wundefined-var-template]
        assert(m_instance != nullptr);
               ^
.../src/common/logger.h:137:21: note: in instantiation of member function 'CSingleton<CLogger>::GetInstancePointer' requested here
    return CLogger::GetInstancePointer();
                    ^
.../src/common/singleton.h:33:15: note: forward declaration of template entity is here
    static T* m_instance;
              ^
.../src/common/singleton.h:44:16: note: add an explicit instantiation declaration to suppress this warning if 'CSingleton<CLogger>::m_instance' is
      explicitly instantiated in another translation unit
        assert(m_instance != nullptr);
               ^
1 error generated.
make[2]: *** [src/CMakeFiles/colobotbase.dir/sound/oalsound/alsound.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/colobotbase.dir/all] Error 2
make: *** [all] Error 2
```

previous step (`cmake ../`) finished successfully. the only warning was "xmlstarlet not found; desktop icons will not be generated".

what's wrong and how to fix that?

thanks!

p.s. current rev # 621911eb64fca6db0701af2b2e960bc8752af521, OS version 10.12.5 (16F73).

**Comment by krzys-h** [comment]
What compiler are you using? Try applying the fix from pull request #963

**Comment by hlopetz** [comment]
that's what i found in cmake log regarding compiler:

```
$ cmake ../
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building Colobot "Gold" (0.1.10-alpha)
-- Build for Mac OSX system
-- Detected Clang version 3.1+
```

**Comment by hlopetz** [comment]
i added [this line](https://github.com/colobot/colobot/pull/963/files#diff-660bfb8efec239adf3bc708732f21498R76) and see the progress.

will update you later.

**Comment by hlopetz** [comment]
seems that issue has been fixed by the patch from #963. there is another one related to inability to create the package without an icon file, but i am going to open a separate case for it.

thanks for your help.

**Comment by tomangelo2** [comment]
If it's fixed then I'll close this issue.

**Comment by krzys-h** [comment]
It's not fixed because I haven't merged that PR yet but don't worry, I will soon.

**Comment by Acionyx** [comment]
Hello, merge all actual PRs, please. It seems there are 9 actual
